version: 2.1
jobs:
  create_image:
    machine: true
    environment:
      DOCKER_TAG: latest
      IMAGE_NAME: srzzumix/icx
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_TOKEN
      - run:
          name: Docker Build
          command: |
            docker build . -t ${IMAGE_NAME}:${DOCKER_TAGE}
      - run:
          name: Docker Push
          command: |
            docker push ${IMAGE_NAME}:${DOCKER_TAGE}
            ./hooks/post_push

orbs:
  docker: circleci/docker@1.4.0

workflows:
  build:
    jobs:
      - create_image:
          filters:
            branches:
              only: main
